source 'git@gitee.com:ocswor/ERSpecs.git'

use_frameworks!

target 'ERComponent_Example' do
    pod 'ERComponent'

  target 'ERComponent_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'

  end
end
